# Generated by Django 4.2.30 on 2026-06-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at'], 'verbose_name': 'service job', 'verbose_name_plural': 'service jobs'},
        ),
        migrations.AddField(
            model_name='employee',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('OFF_DUTY', 'Off duty'), ('EMERGENCY_ONLY', 'Emergency only')], default='AVAILABLE', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='certifications',
            field=models.TextField(blank=True, help_text='Example: EPA 608, electrical safety'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('TECHNICIAN', 'Technician'), ('SENIOR_TECHNICIAN', 'Senior technician'), ('SUPERVISOR', 'Supervisor'), ('DISPATCHER', 'Dispatcher'), ('ADMIN', 'Admin')], default='TECHNICIAN', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='service_area',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.TextField(blank=True, help_text='Example: AC repair, ducting, refrigeration'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='project',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='job_type',
            field=models.CharField(choices=[('INSTALLATION', 'Installation'), ('REPAIR', 'Repair'), ('MAINTENANCE', 'Maintenance'), ('INSPECTION', 'Inspection'), ('EMERGENCY', 'Emergency')], default='REPAIR', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='service_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_JOB', 'On job'), ('ON_LEAVE', 'On leave'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('ON_HOLD', 'On hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
