# Generated by Django 4.2.30 on 2026-06-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_department_employee_daily_incentive_earned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('site_name', models.CharField(max_length=180)),
                ('customer_name', models.CharField(max_length=180)),
                ('contact_person', models.CharField(blank=True, max_length=160)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('site_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('GOVERNMENT', 'Government'), ('OTHER', 'Other')], default='COMMERCIAL', max_length=30)),
                ('property_type', models.CharField(blank=True, max_length=120)),
                ('service_zone', models.CharField(blank=True, max_length=120)),
                ('landmark', models.CharField(blank=True, max_length=180)),
                ('access_instructions', models.TextField(blank=True)),
                ('preferred_visit_time', models.CharField(blank=True, max_length=120)),
                ('equipment_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On hold'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sites', to='office.employee')),
            ],
            options={
                'ordering': ['site_code', 'site_name'],
            },
        ),
    ]
