# Generated by Django 4.2.30 on 2026-06-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('client_name', models.CharField(max_length=180)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('project_name', models.CharField(max_length=180)),
                ('location', models.CharField(max_length=180)),
                ('building_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('HOSPITALITY', 'Hospitality'), ('HEALTHCARE', 'Healthcare'), ('OTHER', 'Other')], default='COMMERCIAL', max_length=30)),
                ('approx_area', models.CharField(blank=True, max_length=80)),
                ('requirement', models.CharField(choices=[('NEW_INSTALLATION', 'New installation'), ('AMC', 'AMC'), ('REPAIR', 'Repair')], default='NEW_INSTALLATION', max_length=30)),
                ('preferred_hvac_system', models.CharField(choices=[('SPLIT_AC', 'Split AC'), ('VRF', 'VRF'), ('CHILLER', 'Chiller'), ('DUCTED', 'Ducted system'), ('PACKAGE_UNIT', 'Package unit'), ('NOT_SURE', 'Not sure')], default='NOT_SURE', max_length=30)),
                ('current_challenges', models.TextField(blank=True)),
                ('budget_range', models.CharField(blank=True, max_length=120)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['client_code', 'client_name'],
            },
        ),
    ]
