# Generated by Django 4.2.30 on 2026-06-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='office.client'),
        ),
    ]
